// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/service/service.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	IRCService_StreamMessages_FullMethodName = "/service.IRCService/StreamMessages"
	IRCService_SendMessage_FullMethodName    = "/service.IRCService/SendMessage"
)

// IRCServiceClient is the client API for IRCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IRCServiceClient interface {
	// Streams messages from the server to the client.
	// The client sends a subscription request (implicitly on connect, or explicit msg).
	StreamMessages(ctx context.Context, opts ...grpc.CallOption) (IRCService_StreamMessagesClient, error)
	// Sends a message to a channel.
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
}

type iRCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIRCServiceClient(cc grpc.ClientConnInterface) IRCServiceClient {
	return &iRCServiceClient{cc}
}

func (c *iRCServiceClient) StreamMessages(ctx context.Context, opts ...grpc.CallOption) (IRCService_StreamMessagesClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IRCService_ServiceDesc.Streams[0], IRCService_StreamMessages_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &iRCServiceStreamMessagesClient{ClientStream: stream}
	return x, nil
}

type IRCService_StreamMessagesClient interface {
	Send(*StreamRequest) error
	Recv() (*StreamEvent, error)
	grpc.ClientStream
}

type iRCServiceStreamMessagesClient struct {
	grpc.ClientStream
}

func (x *iRCServiceStreamMessagesClient) Send(m *StreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *iRCServiceStreamMessagesClient) Recv() (*StreamEvent, error) {
	m := new(StreamEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *iRCServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, IRCService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IRCServiceServer is the server API for IRCService service.
// All implementations must embed UnimplementedIRCServiceServer
// for forward compatibility
type IRCServiceServer interface {
	// Streams messages from the server to the client.
	// The client sends a subscription request (implicitly on connect, or explicit msg).
	StreamMessages(IRCService_StreamMessagesServer) error
	// Sends a message to a channel.
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	mustEmbedUnimplementedIRCServiceServer()
}

// UnimplementedIRCServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIRCServiceServer struct {
}

func (UnimplementedIRCServiceServer) StreamMessages(IRCService_StreamMessagesServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamMessages not implemented")
}
func (UnimplementedIRCServiceServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedIRCServiceServer) mustEmbedUnimplementedIRCServiceServer() {}

// UnsafeIRCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IRCServiceServer will
// result in compilation errors.
type UnsafeIRCServiceServer interface {
	mustEmbedUnimplementedIRCServiceServer()
}

func RegisterIRCServiceServer(s grpc.ServiceRegistrar, srv IRCServiceServer) {
	s.RegisterService(&IRCService_ServiceDesc, srv)
}

func _IRCService_StreamMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IRCServiceServer).StreamMessages(&iRCServiceStreamMessagesServer{ServerStream: stream})
}

type IRCService_StreamMessagesServer interface {
	Send(*StreamEvent) error
	Recv() (*StreamRequest, error)
	grpc.ServerStream
}

type iRCServiceStreamMessagesServer struct {
	grpc.ServerStream
}

func (x *iRCServiceStreamMessagesServer) Send(m *StreamEvent) error {
	return x.ServerStream.SendMsg(m)
}

func (x *iRCServiceStreamMessagesServer) Recv() (*StreamRequest, error) {
	m := new(StreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _IRCService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IRCServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IRCService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IRCServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IRCService_ServiceDesc is the grpc.ServiceDesc for IRCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IRCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.IRCService",
	HandlerType: (*IRCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _IRCService_SendMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMessages",
			Handler:       _IRCService_StreamMessages_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/service/service.proto",
}
